Feature nifi auth
chaordic/ansible-role-nifi pull request #1
Opened 2018-01-23 14:29 UTC by edsoncsouza

2018-01-23 16:33 UTC, mbanton approved these changes
LGTM

2018-01-23 17:10 UTC, raphapr approved these changes

2018-01-23 17:11 UTC, raphapr requested changes

2018-01-23 17:11 UTC, raphapr commented on defaults/main.yml
> +
delete these two last blank lines

2018-01-25 19:41 UTC, edsoncsouza commented on defaults/main.yml
> +
Done :)

2018-01-25 19:43 UTC, raphapr approved these changes

2018-01-26 16:11 UTC, merged